FROM python:3.10

RUN mkdir data
COPY data data/

COPY .env.default .

COPY dist/dp_nlp_berlin_api-*-py3-none-any.whl .

RUN pip install dp_nlp_berlin_api-*-py3-none-any.whl

CMD ["python", "-m", "app.main"]

